version: 5.9.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
install:  
  - ps: $vsixPath = "$($env:USERPROFILE)\Votive2019.vsix"
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/wixtoolset/VisualStudioExtension/releases/download/v1.0.0.3/Votive2019.vsix', $vsixPath)
  - ps: Start-Process "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe" "/q /a $vsixPath" -Wait
  
build_script:
- cmd: >-
    choco install dotnetcore-sdk --pre

    dotnet --list-sdks

    dotnet --version
    
    dotnet restore SecondMonitor.sln  
    
    nuget restore    

    msbuild SecondMonitor.sln /t:Rebuild /p:Configuration=Release /v:m

    powershell "".\generateWixGuid.ps1""

    msbuild WixInstaller\WixInstaller.wixproj /t:Rebuild
test: off
artifacts:
- path: Deployment\
  name: Binaries
- path: Installer\SecondMonitor.msi
  name: Installer
#deploy:
#- provider: GitHub
 # on:
    #appveyor_repo_tag: true
  #description: Relese Description
  #tag: $(APPVEYOR_REPO_TAG_NAME)
  #auth_token:
    #secure: yhQt+R9aeo+1MaDJS5cRZnA8ZGMjlSpTu/y4U2Ity99tDyl3oqE846uvWFx5xndm
  #artifact: Installer
  #draft: true
  
  # here we are going to override common configuration
#for:

# override settings for `master` branch
#- branches:
#    only:
#      - /feat.*/
#  version: 2.5.0.0
